CREATE TABLE Questionario (
	questionarioID int not null primary key auto_increment,
    tipoQuestionario varchar(5) not null,
    dificuldade_para_se_acalmar int(01) not null,
    boca_seca int(01) not null,
    sem_vivencia_possitiva int(01) not null,
    dificuldade_respirar int(01) not null,
    dificuldade_tomar_iniciativa int(01) not null,
    reacao_exagerada int(01) not null,
    sentir_tremores int(01) not null,
    sempre_nervoso int(01) not null,
    situacoes_panico_ridiculo int(01) not null,
    nao_possui_desejo int(01) not null,
    senti_agitado int(01) not null,
    dificuldade_relaxar int(01) not null,
    depressivo_sem_animo int(01) not null,
    intolerante_contratempo int(01) not null,
    entrar_panico int(01) not null,
    nada_entusiasma int(01) not null,
    sem_valor int(01) not null,
    emotivo_sensivel int(01) not null,
    alteracao_cardiaca int(01) not null,
    medo_sem_motivo int(01) not null,
    vida_sem_sentido int(01) not null
);